[build]
  command = "npm install && npm run build"
  publish = "out"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./fresh-start/"

[build.environment]
  NODE_VERSION = "18.17.0"
  NEXT_PUBLIC_API_URL = "https://ai-marketing-hub-backend.onrender.com"
  NPM_FLAGS = "--no-audit --no-fund"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://ai-marketing-hub-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://ai-marketing-hub-backend.onrender.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"

[functions]
  node_bundler = "esbuild"

# Development settings
[dev]
  framework = "next"
  targetPort = 3000

# Plugin configurations
[[plugins]]
  package = "@netlify/plugin-nextjs" 